---
- hosts: webserver
  become: false
  gather_facts: True
  tasks:
   - name: Copy file
     copy:
       src: portopen.py
       dest: /home/lynis/test.py 
   - name: Executing the PYTHON SCRIPT
     command: /home/lynis/test.py 
     register: ServerCheck
   - debug: var={{ item }}
     with_items:
       - ServerCheck.stdout
